# Generated by Django 4.1.7 on 2023-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
